version: '3.8'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 9000:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
  backend:
    image: seasoned132porks/se331-backend-project:latest
    ports:
      - 8999:8080
    environment:
      - JAVA_PROFILR=prod,db
    depends_on:
      - db